#!/usr/bin/env node

const pkg = require('./package.json');
const program = require('commander');

program
  .version(pkg.version)
    .usage('-s <server> [options]')
    .option('-s, --server <server>', 'server to proxy request to', 'http://google.com')
    .option('-h, --host <host>', 'local hostname to listen on', '0.0.0.0')
    .option('-p, --port <port>', 'local port to listen on', 9989)
    .parse(process.argv);

require('./index.js')(program);
